keys:
  - &landrevj age1n9qxxurxhjucwz6l0qc5usywyxvpl9ee0sp3uk9smxq2cs40hg7qlgc3nr
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *landrevj
  - path_regex: secrets/landrevj/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *landrevj